FROM domnikl/schema-registry-gitops:1.9.0

COPY http-exchange.json /opt/http-exchange.json
COPY http-request.json /opt/http-request.json
COPY http-response.json /opt/http-response.json

COPY state1.yml /opt/state1.yml
COPY state2.yml /opt/state2.yml
